name: iOS csdk workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Test plivo IOS using iPhone simulator
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        continue-on-error: true
